import type { Metadata } from 'next';
import { IBM_Plex_Sans } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import Footer from './components/Footer';

const ibmPlexSans = IBM_Plex_Sans({
	variable: '--font-ibm-plex-sans',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'MushaNexa',
	description: 'Generated by create next app',
	icons: {
		icon: './favicon.png',
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className={`${ibmPlexSans.variable} antialiased`}>
			<body className='select-none'>
				<Navbar />
				{children}
				{/* <Footer /> */}
			</body>
		</html>
	);
}
